import localFont from 'next/font/local'
import Header from "@/components/header"
import type { Metadata } from "next";
import "@/styles/main.scss";

const nunito = localFont({
  src: '../../public/fonts/nunito.woff2',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const user = { id: '1', email: 'email', role: 'user', name: 'username' }

  return (
    <html lang="en">
      <body
        className={`${nunito.className} antialiased`}
      >
        <Header user={user} />
        {children}
      </body>
    </html>
  );
}
